import Head from "next/head";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkEperince from "../components/WorkEperince";

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory overflow-scroll z-0 overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Portfolio - Sheheryar Qazi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <section id="hero_section" className="snap-start">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      <section className="snap-center " id="exprience">
        <WorkEperince />
      </section>
      {/* skills */}
 <section id='skills' className='snap-start '>
  <Skills />
 </section>

<section id='projects' className='snap-start'>
  <Projects />
</section>
<section id='contactMe' className='snap-start'>
  <ContactMe />
</section>
    </div>
  );
}
